version: '3.3' 
services:
  mysql: 
    image: mysql:latest
    restart: always 
    environment: 
      MYSQL_DATABASE: 'acit3495' 
      # So you don't have to use root, but you can if you like 
      MYSQL_USER: 'user' 
      # You can use whatever password you like 
      MYSQL_PASSWORD: '2705895a' 
      # Password for root access 
      MYSQL_ROOT_PASSWORD: '2705895a'
    ports: 
      # <Port exposed> : < MySQL Port running inside container> 
      - '3306:3306' 
    expose: 
      # Opens port 3306 on the container 
      - '3306' 
      # Where our data will be persisted 
    volumes: 
      - mysql-data:/var/lib/mysql
  mongo-db: 
    image: mongo:latest
    restart: always 
    environment: 
      MONGO_INITDB_DATABASE: 3495Mongo
    ports: 
      # <Port exposed> : < MySQL Port running inside container> 
      - '27017:27017' 
    expose: 
      # Opens port 3306 on the container 
      - '27017' 
      # Where our data will be persisted 
    volumes: 
      - mongo-data:/data/db
# Names our volume 
volumes: 
  mysql-data:
  mongo-data: